/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SystemsSerialIndexRouteImport } from './routes/systems.$serial.index'
import { Route as SystemsSerialDiagnosticsRouteImport } from './routes/systems.$serial.diagnostics'
import { Route as SystemsSerialEquipmentRouteImport } from './routes/systems.$serial.equipment'
import { Route as SystemsSerialSettingsRouteImport } from './routes/systems.$serial.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsSerialIndexRoute = SystemsSerialIndexRouteImport.update({
  id: '/systems/$serial/',
  path: '/systems/$serial/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsSerialDiagnosticsRoute =
  SystemsSerialDiagnosticsRouteImport.update({
    id: '/systems/$serial/diagnostics',
    path: '/systems/$serial/diagnostics',
    getParentRoute: () => rootRouteImport,
  } as any)
const SystemsSerialEquipmentRoute = SystemsSerialEquipmentRouteImport.update({
  id: '/systems/$serial/equipment',
  path: '/systems/$serial/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsSerialSettingsRoute = SystemsSerialSettingsRouteImport.update({
  id: '/systems/$serial/settings',
  path: '/systems/$serial/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/systems/$serial/diagnostics': typeof SystemsSerialDiagnosticsRoute
  '/systems/$serial/equipment': typeof SystemsSerialEquipmentRoute
  '/systems/$serial/settings': typeof SystemsSerialSettingsRoute
  '/systems/$serial/': typeof SystemsSerialIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/systems/$serial/diagnostics': typeof SystemsSerialDiagnosticsRoute
  '/systems/$serial/equipment': typeof SystemsSerialEquipmentRoute
  '/systems/$serial/settings': typeof SystemsSerialSettingsRoute
  '/systems/$serial': typeof SystemsSerialIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/systems/$serial/diagnostics': typeof SystemsSerialDiagnosticsRoute
  '/systems/$serial/equipment': typeof SystemsSerialEquipmentRoute
  '/systems/$serial/settings': typeof SystemsSerialSettingsRoute
  '/systems/$serial/': typeof SystemsSerialIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostics'
    | '/login'
    | '/settings'
    | '/systems/$serial/diagnostics'
    | '/systems/$serial/equipment'
    | '/systems/$serial/settings'
    | '/systems/$serial/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagnostics'
    | '/login'
    | '/settings'
    | '/systems/$serial/diagnostics'
    | '/systems/$serial/equipment'
    | '/systems/$serial/settings'
    | '/systems/$serial'
  id:
    | '__root__'
    | '/'
    | '/diagnostics'
    | '/login'
    | '/settings'
    | '/systems/$serial/diagnostics'
    | '/systems/$serial/equipment'
    | '/systems/$serial/settings'
    | '/systems/$serial/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SystemsSerialDiagnosticsRoute: typeof SystemsSerialDiagnosticsRoute
  SystemsSerialEquipmentRoute: typeof SystemsSerialEquipmentRoute
  SystemsSerialSettingsRoute: typeof SystemsSerialSettingsRoute
  SystemsSerialIndexRoute: typeof SystemsSerialIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems/$serial/': {
      id: '/systems/$serial/'
      path: '/systems/$serial'
      fullPath: '/systems/$serial/'
      preLoaderRoute: typeof SystemsSerialIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems/$serial/diagnostics': {
      id: '/systems/$serial/diagnostics'
      path: '/systems/$serial/diagnostics'
      fullPath: '/systems/$serial/diagnostics'
      preLoaderRoute: typeof SystemsSerialDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems/$serial/equipment': {
      id: '/systems/$serial/equipment'
      path: '/systems/$serial/equipment'
      fullPath: '/systems/$serial/equipment'
      preLoaderRoute: typeof SystemsSerialEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems/$serial/settings': {
      id: '/systems/$serial/settings'
      path: '/systems/$serial/settings'
      fullPath: '/systems/$serial/settings'
      preLoaderRoute: typeof SystemsSerialSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SystemsSerialDiagnosticsRoute: SystemsSerialDiagnosticsRoute,
  SystemsSerialEquipmentRoute: SystemsSerialEquipmentRoute,
  SystemsSerialSettingsRoute: SystemsSerialSettingsRoute,
  SystemsSerialIndexRoute: SystemsSerialIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
