/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignOutRouteImport } from './routes/sign-out'
import { Route as SystemsSerialIndexRouteImport } from './routes/systems.$serial.index'
import { Route as SystemsSerialDiagnosticsRouteImport } from './routes/systems.$serial.diagnostics'
import { Route as SystemsSerialEquipmentRouteImport } from './routes/systems.$serial.equipment'
import { Route as SystemsSerialSchedulesRouteImport } from './routes/systems.$serial.schedules'
import { Route as SystemsSerialSettingsRouteImport } from './routes/systems.$serial.settings'
import { Route as SystemsSerialPumpsIndexRouteImport } from './routes/systems.$serial.pumps.index'
import { Route as SystemsSerialPumpsSlotIdRouteImport } from './routes/systems.$serial.pumps.$slotId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignOutRoute = SignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsSerialIndexRoute = SystemsSerialIndexRouteImport.update({
  id: '/systems/$serial/',
  path: '/systems/$serial/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsSerialDiagnosticsRoute =
  SystemsSerialDiagnosticsRouteImport.update({
    id: '/systems/$serial/diagnostics',
    path: '/systems/$serial/diagnostics',
    getParentRoute: () => rootRouteImport,
  } as any)
const SystemsSerialEquipmentRoute = SystemsSerialEquipmentRouteImport.update({
  id: '/systems/$serial/equipment',
  path: '/systems/$serial/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsSerialSchedulesRoute = SystemsSerialSchedulesRouteImport.update({
  id: '/systems/$serial/schedules',
  path: '/systems/$serial/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsSerialSettingsRoute = SystemsSerialSettingsRouteImport.update({
  id: '/systems/$serial/settings',
  path: '/systems/$serial/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsSerialPumpsIndexRoute = SystemsSerialPumpsIndexRouteImport.update({
  id: '/systems/$serial/pumps/',
  path: '/systems/$serial/pumps/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsSerialPumpsSlotIdRoute =
  SystemsSerialPumpsSlotIdRouteImport.update({
    id: '/systems/$serial/pumps/$slotId',
    path: '/systems/$serial/pumps/$slotId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/sign-out': typeof SignOutRoute
  '/systems/$serial/diagnostics': typeof SystemsSerialDiagnosticsRoute
  '/systems/$serial/equipment': typeof SystemsSerialEquipmentRoute
  '/systems/$serial/schedules': typeof SystemsSerialSchedulesRoute
  '/systems/$serial/settings': typeof SystemsSerialSettingsRoute
  '/systems/$serial/': typeof SystemsSerialIndexRoute
  '/systems/$serial/pumps/$slotId': typeof SystemsSerialPumpsSlotIdRoute
  '/systems/$serial/pumps/': typeof SystemsSerialPumpsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/sign-out': typeof SignOutRoute
  '/systems/$serial/diagnostics': typeof SystemsSerialDiagnosticsRoute
  '/systems/$serial/equipment': typeof SystemsSerialEquipmentRoute
  '/systems/$serial/schedules': typeof SystemsSerialSchedulesRoute
  '/systems/$serial/settings': typeof SystemsSerialSettingsRoute
  '/systems/$serial': typeof SystemsSerialIndexRoute
  '/systems/$serial/pumps/$slotId': typeof SystemsSerialPumpsSlotIdRoute
  '/systems/$serial/pumps': typeof SystemsSerialPumpsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/sign-out': typeof SignOutRoute
  '/systems/$serial/diagnostics': typeof SystemsSerialDiagnosticsRoute
  '/systems/$serial/equipment': typeof SystemsSerialEquipmentRoute
  '/systems/$serial/schedules': typeof SystemsSerialSchedulesRoute
  '/systems/$serial/settings': typeof SystemsSerialSettingsRoute
  '/systems/$serial/': typeof SystemsSerialIndexRoute
  '/systems/$serial/pumps/$slotId': typeof SystemsSerialPumpsSlotIdRoute
  '/systems/$serial/pumps/': typeof SystemsSerialPumpsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostics'
    | '/login'
    | '/settings'
    | '/sign-out'
    | '/systems/$serial/diagnostics'
    | '/systems/$serial/equipment'
    | '/systems/$serial/schedules'
    | '/systems/$serial/settings'
    | '/systems/$serial/'
    | '/systems/$serial/pumps/$slotId'
    | '/systems/$serial/pumps/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagnostics'
    | '/login'
    | '/settings'
    | '/sign-out'
    | '/systems/$serial/diagnostics'
    | '/systems/$serial/equipment'
    | '/systems/$serial/schedules'
    | '/systems/$serial/settings'
    | '/systems/$serial'
    | '/systems/$serial/pumps/$slotId'
    | '/systems/$serial/pumps'
  id:
    | '__root__'
    | '/'
    | '/diagnostics'
    | '/login'
    | '/settings'
    | '/sign-out'
    | '/systems/$serial/diagnostics'
    | '/systems/$serial/equipment'
    | '/systems/$serial/schedules'
    | '/systems/$serial/settings'
    | '/systems/$serial/'
    | '/systems/$serial/pumps/$slotId'
    | '/systems/$serial/pumps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SignOutRoute: typeof SignOutRoute
  SystemsSerialDiagnosticsRoute: typeof SystemsSerialDiagnosticsRoute
  SystemsSerialEquipmentRoute: typeof SystemsSerialEquipmentRoute
  SystemsSerialSchedulesRoute: typeof SystemsSerialSchedulesRoute
  SystemsSerialSettingsRoute: typeof SystemsSerialSettingsRoute
  SystemsSerialIndexRoute: typeof SystemsSerialIndexRoute
  SystemsSerialPumpsSlotIdRoute: typeof SystemsSerialPumpsSlotIdRoute
  SystemsSerialPumpsIndexRoute: typeof SystemsSerialPumpsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-out': {
      id: '/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof SignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems/$serial/': {
      id: '/systems/$serial/'
      path: '/systems/$serial'
      fullPath: '/systems/$serial/'
      preLoaderRoute: typeof SystemsSerialIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems/$serial/diagnostics': {
      id: '/systems/$serial/diagnostics'
      path: '/systems/$serial/diagnostics'
      fullPath: '/systems/$serial/diagnostics'
      preLoaderRoute: typeof SystemsSerialDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems/$serial/equipment': {
      id: '/systems/$serial/equipment'
      path: '/systems/$serial/equipment'
      fullPath: '/systems/$serial/equipment'
      preLoaderRoute: typeof SystemsSerialEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems/$serial/schedules': {
      id: '/systems/$serial/schedules'
      path: '/systems/$serial/schedules'
      fullPath: '/systems/$serial/schedules'
      preLoaderRoute: typeof SystemsSerialSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems/$serial/settings': {
      id: '/systems/$serial/settings'
      path: '/systems/$serial/settings'
      fullPath: '/systems/$serial/settings'
      preLoaderRoute: typeof SystemsSerialSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems/$serial/pumps/': {
      id: '/systems/$serial/pumps/'
      path: '/systems/$serial/pumps'
      fullPath: '/systems/$serial/pumps/'
      preLoaderRoute: typeof SystemsSerialPumpsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems/$serial/pumps/$slotId': {
      id: '/systems/$serial/pumps/$slotId'
      path: '/systems/$serial/pumps/$slotId'
      fullPath: '/systems/$serial/pumps/$slotId'
      preLoaderRoute: typeof SystemsSerialPumpsSlotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SignOutRoute: SignOutRoute,
  SystemsSerialDiagnosticsRoute: SystemsSerialDiagnosticsRoute,
  SystemsSerialEquipmentRoute: SystemsSerialEquipmentRoute,
  SystemsSerialSchedulesRoute: SystemsSerialSchedulesRoute,
  SystemsSerialSettingsRoute: SystemsSerialSettingsRoute,
  SystemsSerialIndexRoute: SystemsSerialIndexRoute,
  SystemsSerialPumpsSlotIdRoute: SystemsSerialPumpsSlotIdRoute,
  SystemsSerialPumpsIndexRoute: SystemsSerialPumpsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
